### ISSUE TITLE
Feature: User can sign in

### ISSUE THREAD

**Issue by brendan-kormos** [brendan-kormos/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can register / sign in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be able to create an account and sign in

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brendan-kormos/final-project/assets/44518726/ae7a6394-ada1-4b81-a6af-1c5648725d55)
![image](https://github.com/brendan-kormos/final-project/assets/44518726/78348a80-6e43-4e41-921b-83037fa3511d)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to database template

### ☁️ Server Tasks

- [x] Update `server.js` to have a register endpoint and handle request
- [x] Update `server.js` to have a login endpoint and handle request
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] create registration screen
  - [x] include text to register
  - [ ] include username and 2 password prompts that must match
  - [x] include text to sign in if you have an account
- [x] make sure it is compatible on pc and mobile
- [x] create login screen
  - [x] include text to login
  - [x] include username and password prompt
  - [x] include remember me button
  - [x] include text to register if you don't have an account
- [x] make sure it is compatible on pc and mobile
- [x] create sign out button
- [x] code in functionality

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
