### ISSUE TITLE
Feature: User can manage boards

### ISSUE THREAD

**Issue by brendan-kormos** [brendan-kormos/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

create manage projects and boards

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user can click on a plus button to create a project. once the project is created the user can then create boards from the project tab

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brendan-kormos/final-project/assets/44518726/a854408c-5c6c-4eb9-b1a3-4c067d2eda92)
![image](https://github.com/brendan-kormos/final-project/assets/44518726/83ab191f-3970-45cf-acd4-fefda049db7f)
![image](https://github.com/brendan-kormos/final-project/assets/44518726/6329835c-6797-46e9-a0b3-8e3785ae591d)

![image](https://github.com/brendan-kormos/final-project/assets/44518726/2a927a6d-af5c-46db-b0d4-ea4e9d2ce393)
![image](https://github.com/brendan-kormos/final-project/assets/44518726/cc023e70-95af-4475-a2f6-35698c2044ad)
![image](https://github.com/brendan-kormos/final-project/assets/44518726/ab6e6735-aa32-44b0-ad43-c60c462fb23f)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] create test data for `data.sql` 

### ☁️ Server Tasks

- [ ] Update `server.js` to have a create project endpoint
- [ ] Update `server.js` to have a create board endpoint
- [ ] Update `server.js` to have an edit project endpoint
- [ ] Update `server.js` to have an edit board endpoint
- [ ] Update `server.js` to have a delete endpoint for project
- [ ] Update `server.js` to have a delete endpoint for board
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] create a new Projects button in the header
- [ ] create projects and boards layout
- [ ] create the button for creating a project
- [ ] create a modal prompt for editing
- [ ] create a modal prompt for deleting

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
